update yml

diff --git a/ml/preprocessing/segmentation/.gitlab-ci.yml b/ml/preprocessing/segmentation/.gitlab-ci.yml
--- a/ml/preprocessing/segmentation/.gitlab-ci.yml
+++ b/ml/preprocessing/segmentation/.gitlab-ci.yml
@@ -60,15 +60,26 @@ deploy_avicenna_pre_proc_seg_app:
     - docker stop $AVICENNA_PRE_PROC_SEG_TEMP_CONTAINER_NAME || true
     - docker rm $AVICENNA_PRE_PROC_SEG_TEMP_CONTAINER_NAME || true
 
-    - echo "Building the new Docker image with API URLs..."
-    - docker build -t $AVICENNA_PRE_PROC_SEG_IMAGE_NAME -f ml/preprocessing/segmentation/Dockerfile ml/preprocessing/segmentation
+    - echo "Ensuring Docker network '$NETWORK_NAME' exists..."
+    - if ! docker network ls --format '{{.Name}}' | grep -wq "$NETWORK_NAME"; then
+        echo "Network $NETWORK_NAME not found. Creating...";
+        docker network create "$NETWORK_NAME";
+      else
+        echo "Network $NETWORK_NAME already exists.";
+      fi
 
+    - echo "Building the new Docker image with API URLs..."
+    - docker build -t $AVICENNA_PRE_PROC_SEG_IMAGE_NAME \
+        -f ml/preprocessing/segmentation/Dockerfile \
+        ml/preprocessing/segmentation
 
     - echo "Running the new image as a temporary container..."
-    - docker run -d --name $AVICENNA_PRE_PROC_SEG_TEMP_CONTAINER_NAME --network=$NETWORK_NAME  -p $AVICENNA_PRE_PROC_SEG_TEMP_PORT:80 $AVICENNA_PRE_PROC_SEG_IMAGE_NAME
+    - docker run -d --name $AVICENNA_PRE_PROC_SEG_TEMP_CONTAINER_NAME \
+        --network=$NETWORK_NAME \
+        -p $AVICENNA_PRE_PROC_SEG_TEMP_PORT:80 \
+        $AVICENNA_PRE_PROC_SEG_IMAGE_NAME
 
     - echo "Waiting for new container to initialize..."
-    #trigger2
     #- for i in {1..10}; do
     #    if curl -f http://localhost:$AVICENNA_PRE_PROC_SEG_TEMP_PORT/ || curl -f http://localhost:$AVICENNA_PRE_PROC_SEG_TEMP_PORT/index.html; then
     #      echo "Health check passed!";
@@ -89,12 +100,15 @@ deploy_avicenna_pre_proc_seg_app:
       fi
 
     - echo "Starting the new container as $AVICENNA_PRE_PROC_SEG_CONTAINER_NAME..."
-    - docker run -d --name $AVICENNA_PRE_PROC_SEG_CONTAINER_NAME --network=$NETWORK_NAME  -p $AVICENNA_PRE_PROC_SEG_ORIGINAL_PORT:80 $AVICENNA_PRE_PROC_SEG_IMAGE_NAME
+    - docker run -d --name $AVICENNA_PRE_PROC_SEG_CONTAINER_NAME \
+        --network=$NETWORK_NAME \
+        -p $AVICENNA_PRE_PROC_SEG_ORIGINAL_PORT:80 \
+        $AVICENNA_PRE_PROC_SEG_IMAGE_NAME
     
     - docker stop $AVICENNA_PRE_PROC_SEG_TEMP_CONTAINER_NAME || true
     - docker rm $AVICENNA_PRE_PROC_SEG_TEMP_CONTAINER_NAME || true
 
-    - echo "Successfully switched to the new React build on port $AVICENNA_PRE_PROC_SEG_ORIGINAL_PORT."
+    - echo "Successfully switched to the new build on port $AVICENNA_PRE_PROC_SEG_ORIGINAL_PORT."
 
   after_script:
     - echo "Cleaning up old Docker images..."
